apiVersion: v1
kind: Service
metadata:
  name: vidservice-sevice
  namespace: vid-namespace
spec:
  type: NodePort
  selector:
    app: vid-family-app
  ports:
    - targetPort: 8444
      port: 8444
      nodePort: 30080